{
 "title": "Application Monitoring",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "applications",
    "query": "controller, seconds, hours, minutes"
   }
  ]
 },
 "panels": [
  {
   "title": "Requisições por segundo",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (job, status) (rate(http_request_duration_seconds_count[$__interval]))",
     "legendFormat": "{{ job }} - {{ status }}"
    }
   ]
  },
  {
   "title": "Tempo de resposta",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (job, status) (rate(http_request_duration_seconds_sum[$__interval])) / sum by (job, status) (rate(http_request_duration_seconds_count[$__interval]))",
     "legendFormat": "{{ job }} - {{ status }}"
    }
   ]
  },
  { "title": "$applications", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 }, "repeat": "applications" },
  {
   "title": "Requisições por segundo",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (rate(http_request_duration_seconds_count{job=\"app_$applications\"}[$__interval]))",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Tempo médio de resposta",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (job, status) (rate(http_request_duration_seconds_sum{job=\"app_$applications\"}[$__interval])) / sum by (job, status) (rate(http_request_duration_seconds_count{job=\"app_$applications\"}[$__interval]))",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "% reqs servidas em",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (status) (rate(http_request_duration_seconds_bucket{job=\"app_$applications\", le=\"0.01\"}[1m])) / sum by (status) (rate(http_request_duration_seconds_bucket{job=\"app_$applications\", le=\"+Inf\"}[1m])) ",
     "legendFormat": "<= 10ms ({{ status }})"
    },
    {
     "expr": "sum by (status) (rate(http_request_duration_seconds_bucket{job=\"app_$applications\", le=\"0.05\"}[1m])) / sum by (status) (rate(http_request_duration_seconds_bucket{job=\"app_$applications\", le=\"+Inf\"}[1m])) ",
     "legendFormat": "<= 50ms ({{ status }})"
    },
    {
     "expr": "sum by (status) (rate(http_request_duration_seconds_bucket{job=\"app_$applications\", le=\"0.1\"}[1m])) / sum by (status) (rate(http_request_duration_seconds_bucket{job=\"app_$applications\", le=\"+Inf\"}[1m])) ",
     "legendFormat": "<= 100ms ({{ status }})"
    },
    {
     "expr": "sum by (status) (rate(http_request_duration_seconds_bucket{job=\"app_$applications\", le=\"0.5\"}[1m])) / sum by (status) (rate(http_request_duration_seconds_bucket{job=\"app_$applications\", le=\"+Inf\"}[1m])) ",
     "legendFormat": "<= 500ms ({{ status }})"
    }
   ]
  },
  { "title": "$applications", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Requisições por segundo",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (rate(http_request_duration_seconds_count{job=\"app_$applications\"}[$__interval]))",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Tempo médio de resposta",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (job, status) (rate(http_request_duration_seconds_sum{job=\"app_$applications\"}[$__interval])) / sum by (job, status) (rate(http_request_duration_seconds_count{job=\"app_$applications\"}[$__interval]))",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "% reqs servidas em",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (status) (rate(http_request_duration_seconds_bucket{job=\"app_$applications\", le=\"0.01\"}[1m])) / sum by (status) (rate(http_request_duration_seconds_bucket{job=\"app_$applications\", le=\"+Inf\"}[1m])) ",
     "legendFormat": "<= 10ms ({{ status }})"
    },
    {
     "expr": "sum by (status) (rate(http_request_duration_seconds_bucket{job=\"app_$applications\", le=\"0.05\"}[1m])) / sum by (status) (rate(http_request_duration_seconds_bucket{job=\"app_$applications\", le=\"+Inf\"}[1m])) ",
     "legendFormat": "<= 50ms ({{ status }})"
    },
    {
     "expr": "sum by (status) (rate(http_request_duration_seconds_bucket{job=\"app_$applications\", le=\"0.1\"}[1m])) / sum by (status) (rate(http_request_duration_seconds_bucket{job=\"app_$applications\", le=\"+Inf\"}[1m])) ",
     "legendFormat": "<= 100ms ({{ status }})"
    },
    {
     "expr": "sum by (status) (rate(http_request_duration_seconds_bucket{job=\"app_$applications\", le=\"0.5\"}[1m])) / sum by (status) (rate(http_request_duration_seconds_bucket{job=\"app_$applications\", le=\"+Inf\"}[1m])) ",
     "legendFormat": "<= 500ms ({{ status }})"
    }
   ]
  },
  { "title": "$applications", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Requisições por segundo",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (rate(http_request_duration_seconds_count{job=\"app_$applications\"}[$__interval]))",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Tempo médio de resposta",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (job, status) (rate(http_request_duration_seconds_sum{job=\"app_$applications\"}[$__interval])) / sum by (job, status) (rate(http_request_duration_seconds_count{job=\"app_$applications\"}[$__interval]))",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "% reqs servidas em",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (status) (rate(http_request_duration_seconds_bucket{job=\"app_$applications\", le=\"0.01\"}[1m])) / sum by (status) (rate(http_request_duration_seconds_bucket{job=\"app_$applications\", le=\"+Inf\"}[1m])) ",
     "legendFormat": "<= 10ms ({{ status }})"
    },
    {
     "expr": "sum by (status) (rate(http_request_duration_seconds_bucket{job=\"app_$applications\", le=\"0.05\"}[1m])) / sum by (status) (rate(http_request_duration_seconds_bucket{job=\"app_$applications\", le=\"+Inf\"}[1m])) ",
     "legendFormat": "<= 50ms ({{ status }})"
    },
    {
     "expr": "sum by (status) (rate(http_request_duration_seconds_bucket{job=\"app_$applications\", le=\"0.1\"}[1m])) / sum by (status) (rate(http_request_duration_seconds_bucket{job=\"app_$applications\", le=\"+Inf\"}[1m])) ",
     "legendFormat": "<= 100ms ({{ status }})"
    },
    {
     "expr": "sum by (status) (rate(http_request_duration_seconds_bucket{job=\"app_$applications\", le=\"0.5\"}[1m])) / sum by (status) (rate(http_request_duration_seconds_bucket{job=\"app_$applications\", le=\"+Inf\"}[1m])) ",
     "legendFormat": "<= 500ms ({{ status }})"
    }
   ]
  },
  { "title": "$applications", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Requisições por segundo",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (rate(http_request_duration_seconds_count{job=\"app_$applications\"}[$__interval]))",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Tempo médio de resposta",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (job, status) (rate(http_request_duration_seconds_sum{job=\"app_$applications\"}[$__interval])) / sum by (job, status) (rate(http_request_duration_seconds_count{job=\"app_$applications\"}[$__interval]))",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "% reqs servidas em",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (status) (rate(http_request_duration_seconds_bucket{job=\"app_$applications\", le=\"0.01\"}[1m])) / sum by (status) (rate(http_request_duration_seconds_bucket{job=\"app_$applications\", le=\"+Inf\"}[1m])) ",
     "legendFormat": "<= 10ms ({{ status }})"
    },
    {
     "expr": "sum by (status) (rate(http_request_duration_seconds_bucket{job=\"app_$applications\", le=\"0.05\"}[1m])) / sum by (status) (rate(http_request_duration_seconds_bucket{job=\"app_$applications\", le=\"+Inf\"}[1m])) ",
     "legendFormat": "<= 50ms ({{ status }})"
    },
    {
     "expr": "sum by (status) (rate(http_request_duration_seconds_bucket{job=\"app_$applications\", le=\"0.1\"}[1m])) / sum by (status) (rate(http_request_duration_seconds_bucket{job=\"app_$applications\", le=\"+Inf\"}[1m])) ",
     "legendFormat": "<= 100ms ({{ status }})"
    },
    {
     "expr": "sum by (status) (rate(http_request_duration_seconds_bucket{job=\"app_$applications\", le=\"0.5\"}[1m])) / sum by (status) (rate(http_request_duration_seconds_bucket{job=\"app_$applications\", le=\"+Inf\"}[1m])) ",
     "legendFormat": "<= 500ms ({{ status }})"
    }
   ]
  }
 ]
}